# Copyright © 2021 Mark Dumay. All rights reserved.
# Use of this source code is governed by The MIT License (MIT) that can be found in the LICENSE file.

services:
  restic:
    build:
      dockerfile: docker/Dockerfile
      context: .
      args:
        BUILD_VERSION: "${BUILD_VERSION}"
        BUILD_UID: "${BUILD_UID}"
        BUILD_GID: "${BUILD_GID}"
        BUILD_USER: "${BUILD_USER}"
        BUILD_FLAGS: --add-shell --read-only
        BUILD_TARGET: production
        GOLANG_VERSION: "${GOLANG_VERSION}"
        RESTIC_VERSION: "${RESTIC_VERSION}"
    read_only: true
    volumes:
      - type: tmpfs
        target: "/home/${BUILD_USER}"
      - type: tmpfs
        target: /tmp
    environment:
      - RESTIC_LOGLEVEL=${RESTIC_LOGLEVEL}
      - RESTIC_LOGFORMAT=${RESTIC_LOGFORMAT}
      - RESTIC_TIMESTAMP=${RESTIC_TIMESTAMP}
    command: "${RESTIC_CMD}"

    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 120s
      resources:
        limits:
          cpus: "${RESTIC_LIMIT_CPU}"
          memory: "${RESTIC_LIMIT_MEM}"
        reservations:
          cpus: "${RESTIC_RESERVATION_CPU}"
          memory: "${RESTIC_RESERVATION_MEM}"
