version: "3.7"

networks:
  restic:
    name: restic
    driver_opts:
      encrypted: ""

volumes:
  backup:
    name: restic_backup
  restore:
    name: restic_restore

secrets:
  RESTIC_PASSWORD:
    file: secrets/RESTIC_PASSWORD
  B2_ACCOUNT_ID:
    file: secrets/B2_ACCOUNT_ID
  B2_ACCOUNT_KEY:
    file: secrets/B2_ACCOUNT_KEY

services:
  restic:
    image: "markdumay/restic-unattended:${BUILD_VERSION:?version}${IMAGE_SUFFIX:-}"
    restart: unless-stopped
    networks:
      - restic
    volumes:
      - backup:/data/backup:ro
      - restore:/data/restore
    environment:
      - RESTIC_REPOSITORY=${RESTIC_REPOSITORY}
      - RESTIC_PASSWORD_FILE=/run/secrets/RESTIC_PASSWORD
      - B2_ACCOUNT_ID_FILE=/run/secrets/B2_ACCOUNT_ID
      - B2_ACCOUNT_KEY_FILE=/run/secrets/B2_ACCOUNT_KEY
    secrets:
      - RESTIC_PASSWORD
      - B2_ACCOUNT_ID
      - B2_ACCOUNT_KEY