name: Anchore Container Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  scan:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup environment variables
        run: mv sample.env .env

      - name: Set the value
        id: step_one
        run: |
          echo "RESTIC_CMD=restic-unattended check" >> $GITHUB_ENV

      - name: Build a production image
        run: ./dbm/dbm.sh prod build
#         run: ./dbm/dbm.sh prod build --tag markdumay/restic-unattended:latest

#       - name: Run the Anchore scan action
#         uses: anchore/scan-action@main
#         with:
#           image: "markdumay/restic-unattended:latest"
#           acs-report-enable: true

#       - name: Upload Anchore Scan Report
#         uses: github/codeql-action/upload-sarif@v1
#         with:
#           sarif_file: results.sarif
