name: Anchore Container Scan
on: push
jobs:
  Anchore-Build-Scan:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: Build a production image
        run: ./dbm/dbm.sh prod build --tag localbuild/testimage:latest

      - name: Run the Anchore scan action
        uses: anchore/scan-action@main
        with:
          image: "localbuild/testimage:latest"
          acs-report-enable: true

      - name: Upload Anchore Scan Report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
