name: docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: Setup environment variables
        run: mv sample.env .env
        
      - name: Build a development image
        run: ./dbm/dbm.sh build dev

      - name: Build a production image
        run: ./dbm/dbm.sh build prod
