name: docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: Build a development image
        run: ./dbm/dbm.sh dev build

      - name: Build a production image
        run: ./dbm/dbm.sh prod build
